server-port=25565
server-ip=
motd=Tsuna Minecraft Server
max-players=20
online-mode=true
enable-command-block=true
spawn-protection=0
view-distance=8
simulation-distance=6
difficulty=normal
gamemode=survival
pvp=true
allow-flight=true
white-list=false
enforce-whitelist=false
enable-status=true
enable-query=false
enable-rcon=false
network-compression-threshold=256
sync-chunk-writes=false
